#include <map>
#include <string>
#include <QString>


std::map<QString, QString> standard_qtags = 
{
    { "AENC", "Audio encryption"},
    { "APIC", "Attached picture" },
    { "ASPI", "Audio seek point index" },
    { "COMM", "Comments" },
    { "COMR", "Commercial frame" },
    { "ENCR", "Encryption registration" },
    { "EQU2", "Equalisation (2)" },
    { "ETCO", "Event timing codes" },
    { "GEOB", "General encapsulated object" },
    { "GRID", "Group id registration" },
    { "LINK", "Linked information" },
    { "MCDI", "Music CD identifier" },
    { "MLLT", "MPEG lookup table" },
    { "OWNE", "Ownership frame" },
    { "PCNT", "Play counter" },
    { "POPM", "Popularimeter" },
    { "POSS", "Position sync frame" },
    { "PRIV", "Private frame" },
    { "RBUF", "Recommended buffer size" },
    { "RVA2", "Relative volume adj (2)" },
    { "RVRB", "Reverb" },
    { "SEEK", "Seek frame" },
    { "SIGN", "Signature frame" },
    { "SYLT", "Synchronised lyrics" },
    { "SYTC", "Synchronised tempo codes" },
    { "TALB", "Album title" },
    { "TBPM", "Beats per minute" },
    { "TYER", "Year of Release" },
    { "TCOM", "Composer" },
    { "TCON", "Content type" },
    { "TCOP", "Copyright message" },
    { "TDEN", "Encoding time" },
    { "TDLY", "Playlist delay" },
    { "TDOR", "Original release time" },
    { "TDRC", "Recording time" },
    { "TDRL", "Release time" },
    { "TDTG", "Tagging time" },
    { "TENC", "Encoded by" },
    { "TEXT", "Lyricist/Text writer" },
    { "TFLT", "File type" },
    { "TIPL", "Involved people list" },
    { "TIT1", "Work Title/Grouping" },
    { "TIT2", "Title" },
    { "TIT3", "Subtitle" },
    { "TKEY", "Initial key" },
    { "TLAN", "Language(s)" },
    { "TLEN", "Length" },
    { "TMCL", "Musician credits list" },
    { "TMED", "Media type" },
    { "TMOO", "Mood" },
    { "TOAL", "Original album title" },
    { "TOFN", "Original filename" },
    { "TOLY", "Original lyricist" },
    { "TOPE", "Original artist" },
    { "TOWN", "File owner/licensee" },
    { "TPE1", "Artist/Group" },
    { "TPE2", "Album Artist" },
    { "TPE3", "Conductor/performer" },
    { "TPE4", "Interpreted, remixed by" },
    { "TPOS", "Part of a set" },
    { "TPRO", "Produced notice" },
    { "TPUB", "Publisher" },
    { "TRCK", "Track number" },
    { "TRSN", "Internet radio station name" },
    { "TRSO", "Internet radio station owner" },
    { "TSOA", "Album sort order" },
    { "TSOP", "Performer sort order" },
    { "TSOT", "Title sort order" },
    { "TSRC", "ISRC number" },
    { "TSSE", "Settings used for encoding" },
    { "TSST", "Disc/Set subtitle" },
    { "TXXX", "User defined text information" },
    { "UFID", "Unique file identifier" },
    { "USER", "Terms of use" },
    { "USLT", "Unsynchronised lyrics" },
    { "WCOM", "Commercial information" },
    { "WCOP", "Copyright/Legal information" },
    { "WOAF", "Audio file webpage" },
    { "WOAR", "Artist/performer webpage" },
    { "WOAS", "Audio source webpage" },
    { "WORS", "Internet radio station" },
    { "WPAY", "Payment" },
    { "WPUB", "Publishers webpage" },
    { "WXXX", "User defined URL link frame" }
};

std::map<std::string, std::string> standard_tags = 
{
    { "AENC", "Audio encryption"},
    { "APIC", "Attached picture" },
    { "ASPI", "Audio seek point index" },
    { "COMM", "Comments" },
    { "COMR", "Commercial frame" },
    { "ENCR", "Encryption registration" },
    { "EQU2", "Equalisation (2)" },
    { "ETCO", "Event timing codes" },
    { "GEOB", "General encapsulated object" },
    { "GRID", "Group id registration" },
    { "LINK", "Linked information" },
    { "MCDI", "Music CD identifier" },
    { "MLLT", "MPEG lookup table" },
    { "OWNE", "Ownership frame" },
    { "PCNT", "Play counter" },
    { "POPM", "Popularimeter" },
    { "POSS", "Position sync frame" },
    { "PRIV", "Private frame" },
    { "RBUF", "Recommended buffer size" },
    { "RVA2", "Relative volume adj (2)" },
    { "RVRB", "Reverb" },
    { "SEEK", "Seek frame" },
    { "SIGN", "Signature frame" },
    { "SYLT", "Synchronised lyrics" },
    { "SYTC", "Synchronised tempo codes" },
    { "TALB", "Album title" },
    { "TBPM", "Beats per minute" },
    { "TYER", "Year of Release" },
    { "TCOM", "Composer" },
    { "TCON", "Content type" },
    { "TCOP", "Copyright message" },
    { "TDEN", "Encoding time" },
    { "TDLY", "Playlist delay" },
    { "TDOR", "Original release time" },
    { "TDRC", "Recording time" },
    { "TDRL", "Release time" },
    { "TDTG", "Tagging time" },
    { "TENC", "Encoded by" },
    { "TEXT", "Lyricist/Text writer" },
    { "TFLT", "File type" },
    { "TIPL", "Involved people list" },
    { "TIT1", "Work Title/Grouping" },
    { "TIT2", "Title" },
    { "TIT3", "Subtitle" },
    { "TKEY", "Initial key" },
    { "TLAN", "Language(s)" },
    { "TLEN", "Length" },
    { "TMCL", "Musician credits list" },
    { "TMED", "Media type" },
    { "TMOO", "Mood" },
    { "TOAL", "Original album title" },
    { "TOFN", "Original filename" },
    { "TOLY", "Original lyricist" },
    { "TOPE", "Original artist" },
    { "TOWN", "File owner/licensee" },
    { "TPE1", "Artist/Group" },
    { "TPE2", "Album Artist" },
    { "TPE3", "Conductor/performer" },
    { "TPE4", "Interpreted, remixed by" },
    { "TPOS", "Part of a set" },
    { "TPRO", "Produced notice" },
    { "TPUB", "Publisher" },
    { "TRCK", "Track number" },
    { "TRSN", "Internet radio station name" },
    { "TRSO", "Internet radio station owner" },
    { "TSOA", "Album sort order" },
    { "TSOP", "Performer sort order" },
    { "TSOT", "Title sort order" },
    { "TSRC", "ISRC number" },
    { "TSSE", "Settings used for encoding" },
    { "TSST", "Disc/Set subtitle" },
    { "TXXX", "User defined text information" },
    { "UFID", "Unique file identifier" },
    { "USER", "Terms of use" },
    { "USLT", "Unsynchronised lyrics" },
    { "WCOM", "Commercial information" },
    { "WCOP", "Copyright/Legal information" },
    { "WOAF", "Audio file webpage" },
    { "WOAR", "Artist/performer webpage" },
    { "WOAS", "Audio source webpage" },
    { "WORS", "Internet radio station" },
    { "WPAY", "Payment" },
    { "WPUB", "Publishers webpage" },
    { "WXXX", "User defined URL link frame" }
};