#include <map>
#include <string>
#include <QString>


std::map<QString, QString> standard_qtags = 
{
    { "AENC", "Audio encryption"},
    { "APIC", "Attached picture" },
    { "ASPI", "Audio seek point index" },
    { "COMM", "Comments" },
    { "COMR", "Commercial frame" },
    { "ENCR", "Encryption registration" },
    { "EQU2", "Equalisation (2)" },
    { "ETCO", "Event timing codes" },
    { "GEOB", "General encapsulated object" },
    { "GRID", "Group id registration" },
    { "LINK", "Linked information" },
    { "MCDI", "Music CD identifier" },
    { "MLLT", "MPEG lookup table" },
    { "OWNE", "Ownership frame" },
    { "PCNT", "Play counter" },
    { "POPM", "Popularimeter" },
    { "POSS", "Position sync frame" },
    { "PRIV", "Private frame" },
    { "RBUF", "Recommended buffer size" },
    { "RVA2", "Relative volume adj (2)" },
    { "RVRB", "Reverb" },
    { "SEEK", "Seek frame" },
    { "SIGN", "Signature frame" },
    { "SYLT", "Synchronised lyrics" },
    { "SYTC", "Synchronised tempo codes" },
    { "TALB", "Album title" },
    { "TBPM", "Beats per minute" },
    { "TYER", "Year of Release" },
    { "TCOM", "Composer" },
    { "TCON", "Content type" },
    { "TCOP", "Copyright message" },
    { "TDEN", "Encoding time" },
    { "TDLY", "Playlist delay" },
    { "TDOR", "Original release time" },
    { "TDRC", "Recording time" },
    { "TDRL", "Release time" },
    { "TDTG", "Tagging time" },
    { "TENC", "Encoded by" },
    { "TEXT", "Lyricist/Text writer" },
    { "TFLT", "File type" },
    { "TIPL", "Involved people list" },
    { "TIT1", "Work Title/Grouping" },
    { "TIT2", "Title" },
    { "TIT3", "Subtitle" },
    { "TKEY", "Initial key" },
    { "TLAN", "Language(s)" },
    { "TLEN", "Length" },
    { "TMCL", "Musician credits list" },
    { "TMED", "Media type" },
    { "TMOO", "Mood" },
    { "TOAL", "Original album title" },
    { "TOFN", "Original filename" },
    { "TOLY", "Original lyricist" },
    { "TOPE", "Original artist" },
    { "TOWN", "File owner/licensee" },
    { "TPE1", "Artist/Group" },
    { "TPE2", "Album Artist" },
    { "TPE3", "Conductor/performer" },
    { "TPE4", "Interpreted, remixed by" },
    { "TPOS", "Part of a set" },
    { "TPRO", "Produced notice" },
    { "TPUB", "Publisher" },
    { "TRCK", "Track number" },
    { "TRSN", "Internet radio station name" },
    { "TRSO", "Internet radio station owner" },
    { "TSOA", "Album sort order" },
    { "TSOP", "Performer sort order" },
    { "TSOT", "Title sort order" },
    { "TSRC", "ISRC number" },
    { "TSSE", "Settings used for encoding" },
    { "TSST", "Disc/Set subtitle" },
    { "TXXX", "User defined text information" },
    { "UFID", "Unique file identifier" },
    { "USER", "Terms of use" },
    { "USLT", "Unsynchronised lyrics" },
    { "WCOM", "Commercial information" },
    { "WCOP", "Copyright/Legal information" },
    { "WOAF", "Audio file webpage" },
    { "WOAR", "Artist/performer webpage" },
    { "WOAS", "Audio source webpage" },
    { "WORS", "Internet radio station" },
    { "WPAY", "Payment" },
    { "WPUB", "Publishers webpage" },
    { "WXXX", "User defined URL link frame" }
};

std::map<QString, QString> vorbis_qtags = 
{
    {"TITLE", "Track/Work name"}, 
    {"VERSION", "Version of track title (e.g. remix info)"}, 
    {"ALBUM", "Name of album"}, 
    {"TRACKNUMBER", "Track number"}, 
    {"ARTIST", "Artist/Group name"}, 
    {"PERFORMER", "The artist(s) who performed the work"},   
    {"COPYRIGHT", "Copyright attribution"}, 
    {"LICENSE", "License information"}, 
    {"ORGANIZATION", "Record label"}, 
    {"DESCRIPTION", "A short description"},
    {"GENRE", "Genre"},
    {"DATE", "Date recorded"},
    {"LOCATION", "Location recorded"},
    {"CONTACT", "Contact information"},
    {"ISRC", "ISRC number"},
    {"COMPOSER", "Composer name"},
    {"ALBUM ARTIST", "Artist name"},
    {"ALBUMARTIST", "Artist name"},
    {"DISCNUMBER", "Disc Number"},
    {"DISCTOTAL", "Total number of discs"},
    {"TOTALDISCS", "Total number of discs"},
    {"TOTALTRACKS", "Total number of tracks"},
    {"TRACKTOTAL", "Total number of tracks"},
    {"COMMENT", "A short comment"},
    {"MCN", "Media catalog number"},
    {"ALBUMSORT", "Album title sort order"},
    {"DISCSUBTITLE", "Disc/Set subtitle"},
    {"GROUPING", "Content group"},
    {"WORK", "Work title"},
    {"TITLESORT", "Track title sort order"},
    {"SUBTITLE", "Track subtitle"},
    {"PART", "Part"},
    {"OPUS", "Opus number"},
    {"MOVEMENTNAME", "Movement Name"},
    {"ALBUMARTISTSORT", "Album artist sort order"},
    {"ARRANGER", "Arranger name"},
    {"AUTHOR", "Author name"},
    {"WRITER", "Writer name"},
    {"CONDUCTOR", "Conductor name"},
    {"ENGINEER", "Engineer name"},
    {"ENSEMBLE", "Ensemble"},
    {"LYRICIST", "Lyricist name"},
    {"DJMIXER", "Mix-DJ name"},
    {"MIXER", "Mix Engineer name"},
    {"LABEL", "Label name"},
    {"REMIXER", "Remixed by name"},
    {"SOLOISTS", "Names of Soloists"},
    {"MOVEMENT", "Movement number"},
    {"MOVEMENTTOTAL", "Total number of mvts"},
    {"PARTNUMBER", "Part number"},
    {"ORIGINALDATE", "Original release date"},
    {"PERIOD", "Period"},
    {"EAN/UPN", "EAN"},
    {"PRODUCTNUMBER", "Product Number"},
    {"BARCODE", "Barcode"},
    {"CATALOGNUMBER", "Catalog Number"},
    {"LABELNO", "Catalog Number"},
    {"CATALOG", "Catalog Number"},
    {"UPC", "UPC"},
    {"ACOUSTID_ID", "AcoustID"},
    {"ACOUSTID_FINGERPRINT", "AcoustID Fingerprint"},
    {"ACCURATERIPDISCID", "AccurateRip Disc ID"},
    {"ITUNES_CDDB_1", "Itunes CDDB number"},
    {"CDTOC", "CD Table of Contents"},
    {"COMPILATION", "Compilation"},
    {"ENCODED-BY", "Encoded by"},
    {"ENCODER", "Encoding Software"},
    {"ENCODING", "Encoder Settings"},
    {"ENCODER SETTINGS", "Encoder Settings"},
    {"MEDIA", "Release Type/Format"},
    {"SOURCEMEDIA", "Source Media"},
    {"SOURCE", "Source"},
    {"ACCURATERIPRESULT", "AccurateRip Result"},
    {"REPLAYGAIN_ALBUM_GAIN", "Album Replay Gain"},
    {"REPLAYGAIN_ALBUM_PEAK", "Album Replay Gain Peak"},
    {"REPLAYGAIN_TRACK_GAIN", "Track Replay Gain"},
    {"REPLAYGAIN_TRACK_PEAK", "Track Replay Gain Peak"},
    {"WEBSITE", "Track Artist Webpage"},
    {"BPM", "Beats per minute"},
    {"MOOD", "Mood"},
    {"STYLE", "Style"},
    {"METADATA_BLOCK_PICTURE", "Artwork"},
    {"COVERART", "Artwork"},
    {"INSTRUMENT", "Instrument"},
    {"LANGUAGE", "Language"},
    {"RIGHTS", "Rights"},
    {"SCRIPT", "Script"},
    {"LYRICS", "Lyrics"},
    {"DISC", "Disc Number"},
    {"RATING", "Rating"}
};
